"""python run.py ch10_cc --per-kind 3 --seed 1
Writes output/<id>.bundle.json, gas/Archetype_<id>.gs and gas/Units.gs (paste both .gs files into Apps Script)."""
import sys, json, argparse, importlib, collections, os
sys.path.insert(0, "archetypes"); import engine
ap = argparse.ArgumentParser(); ap.add_argument("archetype", help="archetype id, or 'all'"); ap.add_argument("--per-kind", type=int, default=3)
ap.add_argument("--seed", type=int, default=1); a = ap.parse_args()
def one(name):
    A = importlib.import_module(name)
    openers = engine.read_openers(f"content_{name}_openers.csv")
    moves   = engine.read_moves(f"content_{name}_moves.csv")
    out = engine.build(A, a.per_kind, a.seed, openers, moves)
    os.makedirs("output", exist_ok=True); os.makedirs("gas", exist_ok=True)
    json.dump(out, open(f"output/{name}.bundle.json", "w"), indent=1, ensure_ascii=False)
    open(f"gas/Archetype_{name}.gs", "w").write(
      "// GENERATED by the factory. Do not edit by hand. content_version " + out["content_version"] + "\n"
      "var ARCHETYPES = (typeof ARCHETYPES === 'undefined') ? {} : ARCHETYPES;\n"
      f"ARCHETYPES[{json.dumps(name)}] = " + json.dumps(out, ensure_ascii=False) + ";\n"
      "if (typeof module !== 'undefined') module.exports = ARCHETYPES;\n")
    print(f"[{name}] {len(out['variants'])} variants, {len(openers)} openers, {len(moves)} move rows. content_version {out['content_version']}")
    dropped = sum(1 for v in out["variants"] if v.get("dropped"))
    print(f"[{name}] declared numbers per variant: {min(len(v['expected']) for v in out['variants'])}-{max(len(v['expected']) for v in out['variants'])} | variants with a restated-given intermediate removed: {dropped}")
    print(f"[{name}] kinds:", dict(collections.Counter(v["kind"] for v in out["variants"])), "| thrown away:", dict(engine.REJECTS))
    if hasattr(A, "SUBSTANCES"):
        used = {l for o in openers for l in o["fits"]}
        print(f"[{name}] liquids with no scenario yet (never asked):", ", ".join(x[0] for x in A.SUBSTANCES if x[0] not in used) or "none")
    drafts = [s for s, r in moves.items() if r["status"] != "approved"]
    print(f"[{name}] move rows still DRAFT: {len(drafts)} of {len(moves)}")
    for k in engine.REJECTS: engine.REJECTS[k] = 0

import glob
ARCHETYPE_IDS = sorted(os.path.basename(f)[:-3] for f in glob.glob("archetypes/*.py") if not os.path.basename(f).startswith("_"))
for name in (ARCHETYPE_IDS if a.archetype == "all" else [a.archetype]): one(name)
open("gas/Units.gs", "w").write(
  "// GENERATED from units.json by run.py. Do not edit by hand; edit units.json.\n"
  "var UNITS_DATA = " + json.dumps(engine.UNITS, ensure_ascii=False) + ";\n"
  "if (typeof module !== 'undefined') module.exports = UNITS_DATA;\n")
